dist: trusty
sudo: required
language: node_js
node_js:
- '8'
os:
- linux
env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0
  - CHROME_BIN=chromium-browser
  - K8S_OPS_REPO_BRANCH=master
  - K8S_OPS_REPO_SLUG=OpenBudget/budgetkey-k8s
  - DOCKER_IMAGE=budgetkey/budgetkey-app-dashboards
  - DEPLOY_YAML_UPDATE_FILE=values.auto-updated.yaml
  - DEPLOY_VALUES_CHART_NAME=app-dashboards
  - DEPLOY_VALUES_IMAGE_PROP=image
  - DEPLOY_COMMIT_MESSAGE="automatic update of budgetkey-app-dashboards"
  - DEPLOY_GIT_EMAIL=budgetkey-deployer@null.void
  - DEPLOY_GIT_USER=budgetkey-deployer
  - secure: r31rCgTTS+yqjJY8wW0VMyQ7ycuJjiSoUiZaa8dJqzBcEq2q9bhH8YpmR/gjjc6s7Wod/6IjuI44DlbRN8bCzxWLJlW3lneTRIoS9n7Cgb/L2NaDD02HAunqdHqqAddROPXldtoDZS475mkidFC7PSLqgLblzXBQgoztuViur5bZLWiOnQEykclYZqiDc1AC0Bl6MNPvEEU7Naj2+yXQnY9FOD4YJc7K1ag58xXCtR2dfxPlmTuO7QMTNWoxL8JVFw3kSgDamgwjZHN2KvUJC9bt+TztZZWKuTY7qLIGg/E5lRzvdwAntfTPANv27LXWylvPxmHSro7qL/VnjiS0iyDemy1xiaYrU/1xtIkorHLhF31rg+EWH5JecD1qY0v/VIXgZEkEz7uERlnvTxyyZSBIZH8DZ2nH/Ut/+ZlV5AKrW8ooDdoOfEJOH7KO7ZmdcYucFeBFeZ4X0QSqYIY7ahSGOK67fNTvgWPSJH1aGm+ndRhNDpjn2YDQmrmx4wnjeNSM+oZQ7iNLgA/ylq9FYtQKHg0JFhQLa28OkVSViXsS+BV+TqHuMY1fwKu53oHnjbIM8h3ppOvRlxakpoVU5JSzh4HyPJv5JSxYLfdD9pMTiupo7eZ1P7Ynd6rDguxJ12Qcd1EelL1wkntBYx0V/jJvRj419s6uR2Co9LuMCdc=
  - secure: ojVkH656N4EwUqmVwBW12JA5g39BDXpB/VgvqvHxFgRaSXCQDptMv40ITp99ygtQH29MmbbY7EZ3Cx1v3mXKXEUIaspP6ZQskwqTsUOW7hnQd5PjDWof6sO23+EQW02cl4E8EEQGIyqhcLaRVI+9X2JJDZQdvroHftjXW+zWe81sTIrGcDTjuLY7/0cTXNB66J3tKlpiUDWkfV9p8z5JC/VffexzfoD+kGvqYmK3juok2cg9xvJdn6a4rLlcSHwAPL0qa0/1fuoEY7oAa7E5Z2qV6AqJFdplDwvzBRAtB2LeMRUzLtDIh5t7VrJFucuPA5lx1xHM5WGiLg4ZrTcMIqs3Cpmwm15FIQpNDT8MfyCzYufrVKmSW+OXVhNQpp1YypgMVzpqhDBj3GU+ZYMDQ3ZkqcuArAgi9fUgq2TAq+Puvjg4UpmApQvXgT4Z+ouFWXTwzHzNwj3RWhwkKaIHQvIca5Rj3I77ajqrfZlZh6hIKr4rzm5XHgD9FBZoTxEdQUGAQ4qzkGkF9Pg1bFO+I2zNYFHZgcDjDIWLntEGx1jivNpmZkCz8aNLEyigznfbUyolmUpwQWSfmbP854GnU9DjmoOVbJMIkP1kepegxV4WmOtLsnYK3tB2HjW/Ho+MIA2sqXoceYDALMA5eVqGzVeLzzmHJfKjHP5y5iaT3ak=
  - secure: WqQCsdU10NGIz8JoR8M1HeB0vsPn7mEX29VB/8bfoKrJLbS4c+XGrCLkmvWIEB3fIwYJQIlrwSrdIJeslaiFEu0i48HyJjhD1nbCePIdIaXPU4ejCp+IPGkPGpnk0PB5MbI01l/CUb8AGvVjw1z0cpICbrKcHRyJlrliIxH/2w96o7vBYqcurfA5cZyXbUwpyguMXs7YUTbIm3Nb/gqoS6/XTokI0f1gngKSoW3Olat1v43wtFWTU6mDgMJ1w3ntceUdySWT9fzzWJf2XmrflXLvMHKhjtlfe26NuajZILBT7n7xf1klDTCg96Az4WN3CF2mZo6D3LWTTXjDEblkj0Gbbw365brXLVNqfDGekVHEoiA9eNm3tH5Sb/UvMUanvwFdarGBL+wTYWASGAgY66nNeNCGfPkuH0n8fTqkrg1CwwSEMCWrli/Pt9DU/5aBAVEUeWisbTaHIY8jzQrAFWQHs8kIP7SXeFdDx/TxURE8jyTvIsLKo4NlzZV/80QpuR78Kciw4+PxsvW+hu6w2GLI+J/C/KcLrwoLuboWOw9rOhTK9QQ/qeqOXUjiZ9Aszkmvq8eTjTmMw1aThYVeEgxyI/sLOCF970s5Nin3lD5WdzxekPkL/U9UhO8KrBWxe+ARb5Lrl0EkFHrQUgoH4yJfVaPzKZOe7mcqDKoAGpQ=
services:
- docker
before_install:
- curl -s https://raw.githubusercontent.com/OpenBudget/budgetkey-k8s/master/apps_travis_script.sh
  > .travis.sh
- bash .travis.sh script
before_script:
- sh -e /etc/init.d/xvfb start
install:
- npm install
- webdriver-manager update
script:
- npm run lint || true
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
